# Generated by Django 4.1.7 on 2023-03-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredrecipe',
            options={'verbose_name': 'Ингредиент в рецепт', 'verbose_name_plural': 'Ингредиенты в рецепты'},
        ),
        migrations.DeleteModel(
            name='Subscriptions',
        ),
    ]
