# Generated by Django 4.1.7 on 2023-03-11 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_ingredrecipe_options_delete_subscriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredrecipe',
            old_name='name',
            new_name='ingredient',
        ),
    ]
