# Generated by Django 4.1.7 on 2023-03-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_name_ingredrecipe_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=models.CharField(help_text='RGB', max_length=120, unique=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Имя тега'),
        ),
    ]
