# Generated by Django 4.1.7 on 2023-03-18 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_tags_color_alter_tags_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избраный  рецепт', 'verbose_name_plural': 'Избранные рецепты'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Не менее 1')], verbose_name='Время приготовления'),
        ),
    ]
